name: Test Selenium

on:
  push:
    branches:
      - main  

jobs:
  prueba: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2  
      - name: Configurar Python
        uses: actions/setup-python@v2  
        with:
          python-version: "3.10"
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
      - name: Ejecutar pruebas unitarias
        run: |
          python -m unittest discover -s test
      - name: Preparar para despliegue
        run: echo "Listo"
